[package]
name = "awc_config"
version = "0.1.0"
authors = ["Andreas Stührk <andy@hammerhartes.de>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_dhall = "0.10.1"
xdg = "^2.1"
