[package]
name = "awcctl"
version = "0.1.0"
authors = ["Andreas Stührk <andy@hammerhartes.de>"]
edition = "2018"

[dependencies]
clap = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"